import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto("http://localhost:5173", { waitUntil: "networkidle" });
await page.waitForTimeout(3000);
await page.screenshot({ path: "C:/Users/Saurav Kumar/Desktop/overview_verify.png", fullPage: false });
const bodyText = await page.evaluate(() => document.body.innerText);
console.log("Mid Phase count:", (bodyText.match(/Mid Phase/g)||[]).length);
console.log("Early Phase count:", (bodyText.match(/Early Phase/g)||[]).length);
console.log("Recent Phase count:", (bodyText.match(/Recent Phase/g)||[]).length);
console.log("Sample text:", bodyText.substring(0,300));
await browser.close();